resources:
  - name: spboot
    type: git
    source: {uri: "https://github.com/MatthewPJ/spboot.git"}

  - name: spboot-docker-image
    type: docker-image
    source:
      email: "524948894@qq.com"
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/spboot

jobs:
  - name: build-image-job
    plan:
      - get: spboot
        trigger: true
      - task: build-task
        file: spboot/ci/build-task.yml
      - put: spboot-docker-image
        params:
          build: spboot

  - name: deploy-pcf-job
    plan:
      - get: spboot
        passed: [build-image-job]
        trigger: true
      - task: deploy-task
        file: spboot/ci/deploy-task.yml